### ISSUE TITLE
Allow to turn off just some rules in tests

### ISSUE THREAD

**Issue by alenkacz** [scalastyle/scalastyle#150]
I want to ensure that code style is met in tests but right now it appears that I can only disable scalastyle for tests altogether.

I would much more prefer to be able to turn off just some rules, that does not make sense for tests (like MagicNumberChecker or MultipleStringLiteralsChecker)

**Comment by matthewfarwell** [comment]
How do you use Scalastyle - if you're using sbt, then you have a number of options, specify the config in the Test configuration:

    (scalastyleConfig in Test) := baseDirectory.value / "scalastyle-test-config.xml"

**Comment by alenkacz** [comment]
You are right. Actually, I am using gradle and plugin I found did not provide this functionality. But I forked it and will improve it myself. Sorry for this issue!
