### ISSUE TITLE
sbt 0.13.9  scala 2.10.5 not backward compatibility 

### ISSUE THREAD

**Issue by ajozwik** [scalastyle/scalastyle#156]
If class contains `<` the scalastyle parser failed with error:
```
Expected token RBRACKET but got Token(XML_START_OPEN,<,63,<)
```

Infected file:
```
case class EnumWrapper[E <: Enum[E]](a: E
```

Maybe it affects parser, see:
https://github.com/scala/scala/pull/4185

Environment:
sbt 0.13.9
scala 2.10.5 (used by sbt 0.13.9)

**Comment by SethTisue** [comment]
see https://github.com/sbt/sbt/issues/2089

**Comment by ahirreddy** [comment]
I used this snippet to fix it for the time being. It excludes the old version of scalariform and manually uses the new one:
```scala
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.7.0" excludeAll(
  ExclusionRule(organization = "com.danieltrinh")))
libraryDependencies += "org.scalariform" %% "scalariform" % "0.1.7"
```

**Comment by nlochschmidt** [comment]
Any plans on releasing a 0.7.1?

**Comment by SethTisue** [comment]
thanks @ahirreddy for the workaround, this is really helpful

**Comment by fernandomora** [comment]
Could a 0.7.1 version upgraded with scalariform 0.1.7 be released? 
All builds are failing after upgrading to sbt 0.13.9
