### ISSUE TITLE
`TextOutput` ignores the `--verbose` and `--quiet` command-line flags

### ISSUE THREAD

**Issue by Gabriel439** [scalastyle/scalastyle#159]
The `TextOutput` class takes two arguments named `verbose` and `quiet` that both default to `false`:

https://github.com/scalastyle/scalastyle/blob/master/src/main/scala/org/scalastyle/Output.scala#L68

However, the only use of `TextOutput` does not supply these arguments:

https://github.com/scalastyle/scalastyle/blob/bb276857d5841aa863f66e0aca817fef83fecedd/src/main/scala/org/scalastyle/Main.scala#L112

... so they always default to `false`, even if the user supplies `--verbose` or `--quiet` on the command line.

I can submit a pull request to fix this if that is okay with you.

**Comment by Gabriel439** [comment]
A corollary of this issue is that the `--verbose` flag is actually completely ignored by `scalastyle`

**Comment by matthewfarwell** [comment]
A PR would be great.
