### ISSUE TITLE
Is println bad? 

### ISSUE THREAD

**Issue by xanderdunn** [scalastyle/scalastyle#161]
The default scalastyle config that's provided with it has `println` flagged as a warning in both the token and regex rules:
```xml
 <check class="org.scalastyle.file.RegexChecker" level="warning" enabled="true">
  <parameters>
   <parameter name="regex"><![CDATA[println]]></parameter>
  </parameters>
 </check>
```

Is this just an example that isn't meant for production use, or is `println` considered bad?

**Comment by matthewfarwell** [comment]
It is just an example. There is nothing wrong with println.

However, for production code, there are better solutions, for example slf4j or log4j. So, a number of project that I have been involved with discourage the use of println. See, for example http://stackoverflow.com/questions/2750346/logger-vs-system-out-println

**Comment by xanderdunn** [comment]
@matthewfarwell Thanks.  Good advice.

**Comment by eshu** [comment]
> It is just an example. There is nothing wrong with println.
> 
> However, for production code, there are better solutions, for example slf4j or log4j. So, a number of project that I have been involved with discourage the use of println. See, for example http://stackoverflow.com/questions/2750346/logger-vs-system-out-println

There is ```PrintStream``` in the standard Java library, it has ```println``` in its methods and this check complains about it too. I updated the regular expression for my project:
```
 <check level="warning" class="org.scalastyle.file.RegexChecker" enabled="true">
  <parameters>
   <parameter name="regex"><![CDATA[(?<!\.)println]]></parameter>
  </parameters>
 </check>
```
Probably it should be in the scalastyle default configuration: the warning appears only for "bare" ```println``` call.
