### ISSUE TITLE
SpacesAfterPlusChecker should ignore covariant and type declarations

### ISSUE THREAD

**Issue by SanityResort** [scalastyle/scalastyle#164]
If you use the SpacesAfterPlusChecker the following class declaration will lead to an error:

trait MyTrait[+T <: SomeOtherClass]

The checker requires to add a space to make it look like: 

trait MyTrait[+ T <: SomeOtherClass]

While this compiles and works, it is still pretty bothersome, especially since code formatters usually remove the space again.

**Comment by matthewfarwell** [comment]
Closing, presumed no longer a problem.

**Comment by SanityResort** [comment]
Has there been a fix? Or why is this considered "no longer a problem"?

**Comment by matthewfarwell** [comment]
This seems to work in master. Can you recheck please?.
