### ISSUE TITLE
EnsureSingleSpaceBeforeTokenChecker false positives for `{` and string interpolation

### ISSUE THREAD

**Issue by dragos** [scalastyle/scalastyle#178]
It's usually good practice to ensure a space before `{`, like in `map { .. }`. However, the token checker will fire errors for string interpolation `s"blah ${foo._1}"`.

**Comment by wickedshimmy** [comment]
Also in e.g. `import scala.{Foo, Bar}`

**Comment by matthewfarwell** [comment]
EnsureSingleSpaceBeforeTokenChecker is a generic checker which covers all use of the token. If there is a specific rule required for braces, then we need to write a specific rule for it.
