### ISSUE TITLE
scalastyle integrated with coala!

### ISSUE THREAD

**Issue by ravinimmi** [scalastyle/scalastyle#189]
Hi, We are [coala](http://coala-analyzer.org/) (Language Independent Code Analysis Application). We are now using scalastyle as linting tool for our Scala support [(Scala linting feature request)](https://github.com/coala-analyzer/coala-bears/issues/64).

You can have a chat with us anytime at https://gitter.im/coala-analyzer/coala. We will be happy to work together. We are a pretty active community so you will always find someone on [gitter](https://gitter.im/coala-analyzer/coala) :)

**Comment by sils1297** [comment]
This gets you some editor integrations and a few additional output formats you might not have yet so it might be valuable for your users and you could, if you wanted to rely on us, stop worrying too much about user interaction. That's the goal of coala basically, stripping away the awful stuff from static code analysis writing ;).

**Comment by matthewfarwell** [comment]
Cool. That sounds great. Anything I can do to help, just shout.
