### ISSUE TITLE
Warning msg for class/object names not capitalized?

### ISSUE THREAD

**Issue by danyaljj** [scalastyle/scalastyle#190]
Is there any warning msg for class/object names not capitalized?

fyi @bhargav

**Comment by mjp4** [comment]
This has been fixed in https://github.com/scalastyle/scalastyle/pull/219 (not merged as of 23/09/2016)

**Comment by mjp4** [comment]
> The ClassNamesChecker and ObjectNamesChecker are not checking the entire name.  Therefore the regex passes as long as a capitalised letter appears anywhere in the name.  
Therefore `Object`, `ObjectName` and `objectName` are passing the check, but `object` was not. Only the first two should have passed.

**Comment by matthewfarwell** [comment]
Fixed by #219
