### ISSUE TITLE
PublicMethodsHaveTypeChecker reports errors on private class

### ISSUE THREAD

**Issue by joost-de-vries** [scalastyle/scalastyle#192]
In the code underneath the `id` function is private. Because the class is private. But PublicMethodsHaveTypeChecker reports an error on it as a public function.
Now I have to prefix `id` and all of its sibling functions with a `private[somepackage]` statement. 
Which feels like Java style boiler plate code.

``` scala
package mypackage

class AClassThatUsesTheClassbelow() {
  val dbConfig = dbConfigProvider.get[JdbcProfile]

  private val something = TableQuery[Something]

// snip
}

private[mypackage] class Something(tag: Tag) extends Table[Bla](tag, "Something") {

  def id = column[Option[Long]]("ID", O.PrimaryKey, O.AutoInc)

//etc
}
```

Btw scalastyle is a great tool. :smiley:

**Comment by matthewfarwell** [comment]
Yeah, I thought about this, but I came up with the following use case of a factory method:

```
trait Bar {
  def x(): Int
}

class Xxx {
  private class BarImpl(value: Int) extends Bar {
    def x(): Int = value
  }

  def factory(): Bar = new BarImpl(5)
}
```

The method is still public, even though it is inside a private class. I guess we could add an option to ignore private classes for this checker.  I think most things would be caught by the compiler, probably. What do you think?
