### ISSUE TITLE
Should capture the unused import

### ISSUE THREAD

**Issue by ysihaoy** [scalastyle/scalastyle#193]
I would like a rule which can detect whether there are some unused import in the code.

**Comment by matthewfarwell** [comment]
This isn't generally possible in Scalastyle. It doesn't know about types.

**Comment by espertus** [comment]
I understand that it would be hard to tell if wildcard imports are unused, but would this work for non-wildcard imports?

To determine whether `import foo.bar.Baz' is useful, check whether `Baz` appears subsequently in the program:

- not in an import
- not in a comment
- not in a String
- not preceded by `foo.bar.`
