### ISSUE TITLE
FieldNamesChecker does not handle unpacking into tuple

### ISSUE THREAD

**Issue by frohman-wd** [scalastyle/scalastyle#199]
The FieldNamesChecker assumes that in the statement `val (obj1, obj2) = unpack(obj)`, `(obj1, obj2)` is the field name instead of recognizing that there are two field names in the statement, `obj1` and `obj2`.  That means that the FieldNamesChecker prevents you from using this syntax without getting flagged.

**Comment by hasumedic** [comment]
Is there a work around for this? What's Scalastyle actually checking against when it finds this format? From the few tests I run it seems that it receives something that starts with `(` but that doesn't end with `)`.

**Comment by jqno** [comment]
I'm running into this issue as well.

@hasumedic Given the expression `val (obj1, obj2) = unpack(obj)`, and given your regex, does that mean Scalastyle only picks up the `(obj1` part? (i.e., including the opening `(` but excluding the `,` and everything after)

**Comment by hasumedic** [comment]
My guess is that given `val (obj1, obj2) = unpack(obj)`, what scalastyle tries to compare with the regex would just be `(`, ignoring `obj1, obj2)`.

**Comment by jqno** [comment]
@hasumedic Ah ok, I mis-read your regex.
I thought that at least I could check the first name (by prepending the regex with an optional `(`) but I guess that's not possible either.

**Comment by graingert** [comment]
it also doesn't handle unapply assignments

**Comment by graingert** [comment]
```scala
val Foop(ham, spam) = someFoop;
```

**Comment by graingert** [comment]
checkout this regex for a hack: https://github.com/socrata-platform/socrata-sbt-plugins/pull/37#issue-96905985

@sokrahta I can't work out how to get it working for tuples:

var (ham, spam) = someTuple2;

**Comment by graingert** [comment]
These regexes no longer work for tuple unpacking because: https://github.com/scalastyle/scalastyle/blob/master/src/main/scala/org/scalastyle/scalariform/ClassNamesChecker.scala#L175

is checking against 
```
List(
  Token(VAL,'val',0,'val'),
  Token(LPAREN,(,4,'('),
)
```

because the LPAREN is tokenized on its own.

**Comment by graingert** [comment]
@matthewfarwell Any chance we can get this working by pattern matching on PatDefOrDcl and recursively descending into it?

So we can support all sorts of strange things like:

```scala
val List(Tuple2((foo, bar), (foo))) = foop;
```

**Comment by matthewfarwell** [comment]
@graingert Yes, you'll have to change FieldNamesChecker from a simple token check to a recursive descent.
