### ISSUE TITLE
Scalastyle should highlight file name, line number in IDE

### ISSUE THREAD

**Issue by JohnReedLOL** [scalastyle/scalastyle#200]
&nbsp;&nbsp; Your style checker gives me a file name and line number, but in IntelliJ I have to manually go to each of those locations. I would like a feature which can format the class names and line numbers to facilitate go-to-location.

Example:
- [http://i.imgur.com/MNNkYXe.png](http://i.imgur.com/MNNkYXe.png)

**Comment by matthewfarwell** [comment]
You can use the Intellij plugin for this. If this doesn't work, please reopen the issue.
