### ISSUE TITLE
Wrong check for open Multi-Line Comment

### ISSUE THREAD

**Issue by felixnext** [scalastyle/scalastyle#202]
I encountered an issue that does not correctly check comment start _inside_ of comments. So for example:

``` scala
def test() {
  println("sample")
  /*
  foo bar
  /*
  baz
  */
}
```

This will be detected as two opened multi-line comments. Since there is only one closing the closing bracket is seen as inside a comment, throwing an error.

**Comment by matthewfarwell** [comment]
Yes, this seems to be a problem. The problem is in scalariform.

**Comment by matthewfarwell** [comment]
This isn't valid Scala, at least in 2.11.
