### ISSUE TITLE
feature request: enforce JavaDoc or ScalaDoc indentation

### ISSUE THREAD

**Issue by ceedubs** [scalastyle/scalastyle#211]
The official indentation recommendation for ScalaDoc is:

``` scala
/**
  * Does stuff.
  */
```

However, many projects have adopted the JavaDoc-style indentation:

``` scala
/**
 * Does stuff.
 */
```

It would be nice to be able to add a scalastyle rule to enforce one or the other (in my case I'm interested in enforcing consistent JavaDoc-style indentation).

Note: #188 mentions that `IndentationChecker#isTabAlligned` enforces the JavaDoc-style. However, I would be interested in a less restrictive rule that only applies to comments, as `isTabAligned` doesn't play nicely with some styles of code formatting that I tend to like.

**Comment by mpilquist** [comment]
Note that scalafmt supports this changing this automatically: https://olafurpg.github.io/scalafmt/#Formattingrules

**Comment by matthewfarwell** [comment]
I think that would be a good option. A PR would be wonderful.
