### ISSUE TITLE
Add the support to check Java's @Override annotation (OverrideJavaChecker)

### ISSUE THREAD

**Issue by HyukjinKwon** [scalastyle/scalastyle#214]
I see Java's `@Deprecated` can be checked with [`DeprecatedJavaChecker`](https://github.com/scalastyle/scalastyle/blob/master/src/main/scala/org/scalastyle/scalariform/DeprecatedJavaChecker.scala) but it might be nicer if we have a rule for preventing `@Override` as well.

**Comment by matthewfarwell** [comment]
Good idea. Do you want to do the PR?

**Comment by HyukjinKwon** [comment]
I am afraid I am not used to the code base here. Is it okay to give a shot though referring `DeprecatedJavaChecker`?

**Comment by canoztokmak** [comment]
@HyukjinKwon yes, I guess it will be quite similar to `DeprecatedJavaChecker` implementation.

**Comment by canoztokmak** [comment]
submitted https://github.com/scalastyle/scalastyle/pull/245 for this issue.

**Comment by HyukjinKwon** [comment]
Thank you.

**Comment by matthewfarwell** [comment]
#245 has been merged. Closing.

**Comment by HyukjinKwon** [comment]
Thanks for dealing with this @canoztokmak and @matthewfarwell. I am eager to try this in a new release!
