### ISSUE TITLE
Parameter for UnderscoreImportChecker to allow underscore import exceptions

### ISSUE THREAD

**Issue by kevincairo** [scalastyle/scalastyle#220]
### Feature request:

Currently `UnderscoreImportChecker` accepts no parameters. It seems useful to be able to allow underscore import from:
- whitelisted types (ex: `JavaConverters._`)
- a companion object

Not terribly difficult to use comment filters, but if it's straightforward to add, would be nice to have.

**Comment by joearasin** [comment]
Another couple places where whitelisting would be useful:
 - JSON serialization w/ spray-json
 - scala.concurrent.duration._

**Comment by matthewfarwell** [comment]
Fixed in #232.
