### ISSUE TITLE
Function argument name checker

### ISSUE THREAD

**Issue by dskrvk** [scalastyle/scalastyle#222]
I saw this proposed in [scalastyle-users](https://groups.google.com/d/topic/scalastyle-users/ZKeL8qwUreo/discussion) a while ago, but didn't find an open issue.

Seems like an obvious and useful feature?

**Comment by matthewfarwell** [comment]
That post is from 5 years ago. Which feature are you talking about?

**Comment by dskrvk** [comment]
See title - a checker for function argument names. This doesn't seem to be covered by the variable name checker - e.g. I can use an all-caps name in the arguments, but if I try to declare such a name in the function body, I get a warning.

**Comment by matthewfarwell** [comment]
Good idea. A PR would be fantastic.

**Comment by canoztokmak** [comment]
Submitted https://github.com/scalastyle/scalastyle/pull/244 for this issue.

**Comment by canoztokmak** [comment]
This can be closed as the solution is merged.

**Comment by matthewfarwell** [comment]
Fixed by #244
