### ISSUE TITLE
ScalaDocChecker doesn't support comments inheritance

### ISSUE THREAD

**Issue by NikolaySl** [scalastyle/scalastyle#224]
According to Scala documentation the comments have implicit inheritance:
http://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html#comment-inheritance
https://wiki.scala-lang.org/display/SW/Syntax#Syntax-CommentInheritance

But ScalaDocChecker  requires comment for overridden methods in spite the fact that parent method has the correct one.

**Comment by matthewfarwell** [comment]
Scalastyle doesn't know about stuff outside of the current file, so if your parent class is in a different file, then there is no way for it to know if a method has already got scaladoc. One option would be to add a ignoreOverride parameter, which if true, ignores methods which have the override keyword. If this is acceptable, then a PR would be great :-)
