### ISSUE TITLE
ScalaDocChecker fails valid constrained type parameter declarations

### ISSUE THREAD

**Issue by MichaelJAllen** [scalastyle/scalastyle#225]
Consider the following:

```
/**
 * Some generic trait.
 *
 * @tparam T Some type parameter.
 */
trait SomeTrait[T <: SomeTrait[T]]
```

The ScalaDocChecker flags this as follows:

```
[warn] /some/path/SomeTrait.scala:6: Missing or badly formed Scaladoc: Malformed @tparams
```

If I remove the constraint from the declaration of the type parameter, then the ScalaDocChecker passes:

```
/**
 * Some generic trait.
 *
 * @tparam T Some type parameter.
 */
trait SomeTrait[T]
```

Incidentally, my ScalaDocChecker is configured as follows:

```
<check class="org.scalastyle.scalariform.ScalaDocChecker" enabled="true" level="warning" />
```

**Comment by dreadedsoftware** [comment]
I just started using scalastyle and am running into this very issue. Is there any update here? If not, could you point me to somewhere in the code? I am willing to work this, it will be a thorn in my side pretty soon.

This bug shows no matter the bound used
`/**
 * 1
 * @tparam A a
 */
trait T1[A] //works fine
/**
 * 2
 * @tparam A a
 */
trait T2[A <: Any] //upper bound broken
/**
 * 3
 * @tparam A a
 */
trait T3[A >: Nothing] //lower bound broken
/**4*/
trait T4 { //works fine
  /**
   * 4.1
   * @tparam A a
   */
  def t1[A <% String]: Unit //view bound broken
  /**
   * 4.2
   * @tparam A a
   */
  def t2[A: Option]: Unit //context bound broken
}
/**
 * 5
 * @tparam A a
 */
trait T5[+A] //works fine
/**
 * 6
 * @tparam A a
 */
trait T6[-A] //works fine
/**
 * 7
 * @tparam A a
 */
trait T7[A[_]] //works fine`
