### ISSUE TITLE
Rule request: Allow omitted return type for implementations of abstract methods

### ISSUE THREAD

**Issue by PapaCharlie** [scalastyle/scalastyle#229]
For classes that extend traits or abstract classes, the return type of a public method is redundant. In other words:

```
trait Foo {
  def bar: Int
}

class Bar extends Foo {
  def bar = 1
}
```

The method `bar` in the `Bar` class doesn't need to have the type annotation, as it is already defined in the `Foo` trait.

On the other hand, it would still be nice to enable this rule to enforce/suggest that public methods that *aren't* implementations must/should have the type annotation.

**Comment by matthewfarwell** [comment]
This isn't possible in a generic way in Scalastyle. It only knows about details in the current file.
