### ISSUE TITLE
enforce keyword arguments for duplicate types

### ISSUE THREAD

**Issue by graingert** [scalastyle/scalastyle#231]
if you have a 

```scala
case class Foo (
  id: String,
  relatedId: String,
  somethingElse: SomethingElse
)
```

It would be handy to enforce:

```scala
// good
Foo(id="ham", relatedId="spam", thing)

// bad
Foo("ham", "spam", thing)
```

**Comment by graingert** [comment]
eg if there are duplicated parameters, you must always disambiguate with keyword args.

**Comment by matthewfarwell** [comment]
Scalastyle only "knows" about things in the same physical file, so this isn't possible. Also, it is quite hard to know which constructor or apply method you're calling.

**Comment by matthewfarwell** [comment]
Not possible with Scalastyle.

**Comment by graingert** [comment]
Should probably kill this rule then
