### ISSUE TITLE
EqualsHashCode checks for Object not Any

### ISSUE THREAD

**Issue by channingwalton** [scalastyle/scalastyle#235]
The EqualsHashCode check is looking for classes whose equals method overrides `def equals(other: Object)` rather than `def equals(other: Any)`.

**Comment by matthewfarwell** [comment]
Don't understand this one. If I have the following file:

`class XxxJLObject {
  def equals(f: java.lang.Object): Boolean = ???
}

class XxxAny {
  def equals(f: Any): Boolean = ???
}`

Then scalastyle warns about both classes. At least in master. Are you expecting some other behaviour?

**Comment by channingwalton** [comment]
Hi, thanks for checking. I'll try again at work to confirm.

**Comment by channingwalton** [comment]
Yes you're right - sorry. The warning given in both cases is that "Covariant equals without overriding equals(java.lang.Object)" which confused me.

**Comment by matthewfarwell** [comment]
Closing this issue.
