### ISSUE TITLE
Any rules for right bracket checker? 

### ISSUE THREAD

**Issue by lostMohican** [scalastyle/scalastyle#238]
Hi, 

I've started using Scalastyle but I couldn't find any rules(looked at here http://www.scalastyle.org/rules-0.8.0.html) regarding space around the right brackets. 

1. Is there a way to match right brackets as well? 
2. Is right bracket support a work in progress? 
3. If not, are there any reasons to why this work is not being done? 

Thanks,
Erkin

**Comment by matthewfarwell** [comment]
No, there aren't currently rules for the right bracket. If you wish to contribute, you are welcome to submit a PR.

**Comment by canoztokmak** [comment]
Submitted https://github.com/scalastyle/scalastyle/pull/240 for this issue. Please have a look.

**Comment by lostMohican** [comment]
Hi, I've seen that this pull request is merged. Do you have plans for a release anytime soon? 

Thanks

**Comment by matthewfarwell** [comment]
Yes. Probably in the next couple of weeks, depending upon how things go.
