### ISSUE TITLE
Add parameter ignoreComments to MethodLengthChecker

### ISSUE THREAD

**Issue by tanishiking** [scalastyle/scalastyle#247]
Hi
`MethodLengthChecker` counts method length ( **including comment lines** ) and if the length is greater than maxLength, the method would be reported.

I think it would be nice to add a parameter to MethodLengthChecker that ignores comment lines. (named `ignoreComments` or something)

For example, if the parameter is set to true, the method1's length would be 3 (instead of 9)

```scala
class foo() {
  def method1(): Unit = {
    val x = 1
    /*
     * some comment
     */
    val y = 1
    // some comment
    // some comment
    // some comment
    x + y
  }
}
```

---

This issue is related to https://github.com/scalastyle/scalastyle/issues/166
I agree that it's not good idea to change the behaviour by default.

I want to add a parameter (by default it is set to false). If the parameter set to true, `MethodLengthChecker` ignores comments.

**Comment by tanishiking** [comment]
And submitted PR https://github.com/scalastyle/scalastyle/pull/248

**Comment by matthewfarwell** [comment]
#248 has been merged. Closing
