### ISSUE TITLE
EmptyClassChecker documentation inconsistency

### ISSUE THREAD

**Issue by mjenczmyk** [scalastyle/scalastyle#262]
According to the documentation `org.scalastyle.scalariform.EmptyClassChecker` should check whether there are no braces whenever class/trait has no members. I tried to use that rule in my scalastyle configuration, but there seems to be inconsistency.

`class Foo()` seems to be linted without any warning, although `trait Foo()` and `object Foo()` seem to raise a warning. After reading the docs I would assume that `class Foo()` should also raise a warning (I'm not sure what about `object Foo()`).

Here is a `EmptyClassChecker` entry in my scalastyle configuration:

`<check level="warning" class="org.scalastyle.scalariform.EmptyClassChecker" enabled="true"/>` 

I'm using `sbt` 0.13.13, `scala` 2.12.2, `scalastyle` 0.8.0.

**Comment by matthewfarwell** [comment]
Can you provide a small example of the problem please?

**Comment by mjenczmyk** [comment]
I'm sorry for a misunderstanding - when I was submitting the issue I misunderstood what this rule is actually checking - everything seems to work fine. If you don't mind issue can be closed.

**Comment by matthewfarwell** [comment]
OK.
