### ISSUE TITLE
scalastyle_config.xml not working at all in the intellij plugin

### ISSUE THREAD

**Issue by selvavalluvan** [scalastyle/scalastyle#263]
I have my scalastyle_config.xml inside <root>/project directory and I am testing with only one check, HeaderMatchesChecker.
![screen shot 2017-07-21 at 11 15 37 am](https://user-images.githubusercontent.com/5952660/28476769-12788006-6e06-11e7-85f8-fbd5947eab8f.png)
Now I have the scala file called Hello.scala.
![screen shot 2017-07-21 at 11 17 20 am](https://user-images.githubusercontent.com/5952660/28476796-31b4ed24-6e06-11e7-8c81-1dd2ac729367.png)
Clearly, the file doesn't have a checker and Intellij is not showing any warnings/errors.

What am I missing here. I enabled scalastyle in the intellij scala plugin and I tried adding the file to <root>/.idea directory as well.

I am happy to provide more details as well.

**Comment by matthewfarwell** [comment]
Personally, I put scalastyle_config.xml into the project directory as well, so I'm fairly sure that this will work. If you put another checker into the file, does that checker get picked up? Maybe http://www.scalastyle.org/rules-0.9.0.html#org_scalastyle_scalariform_NullChecker or similar. If this rule works and your header doesn't, then it may be a problem with the regex. Try with a simpler string.

**Comment by selvavalluvan** [comment]
Solved it! Actually nothing wrong with the config or the placement of the file. It was because my intellij scala plugin. I had two plugins and it was contradicting each other. Fixed by keeping the official intellij scala plugin. Thanks for the response @matthewfarwell .
