### ISSUE TITLE
FieldNamesChecker issues

### ISSUE THREAD

**Issue by ericbn** [scalastyle/scalastyle#265]
If using

    <check level="warning" class="org.scalastyle.scalariform.FieldNamesChecker" enabled="true">
     <parameters>
      <parameter name="regex">^[a-z][A-Za-z0-9]*$</parameter>
      <parameter name="objectFieldRegex">^[A-Z][A-Za-z0-9]*$</parameter>
     </parameters>
    </check>

FieldNamesChecker does not like tuple pattern matching with types, like:

    val (foo: Foo, bar: Bar) = baz

It complains with:

    Field name does not match the regular expression '^[a-z][A-Za-z0-9]*$'

at the position where the "Foo" and "Bar" strings start.

Also, the [Scala Style Guide](http://docs.scala-lang.org/style/naming-conventions.html#constants-values-variable-and-methods) suggests we use upper camel case for constants, which would account just for `val`s in objects, but not `var`s. And `objectFieldRegex` is being applied in both cases, so not offering enough granularity for checking just for constant names.

**Comment by matthewfarwell** [comment]
Which version is this using? There was some work done on destructuring in 0.9.0. If you're not using that version, can you try with it please?

**Comment by ericbn** [comment]
Forgot to mention, I'm using

    addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.9.0")

**Comment by matthewfarwell** [comment]
Ok. Thanks. I'm not around for the next 2 weeks, I'll look at it after that.
