### ISSUE TITLE
ScalaDocChecker indentStyle & ignoreOverride documentation inaccurate

### ISSUE THREAD

**Issue by MichaelJAllen** [scalastyle/scalastyle#266]
The [documentation](http://www.scalastyle.org/rules-0.9.0.html#org_scalastyle_scalariform_ScalaDocChecker) for the new `indentStyle` and `ignoreOverride` parameters of the `ScalaDocChecker` is misleading. The documentation (and default configs) are expressed along the following lines:

```xml
<check enabled="true" class="org.scalastyle.scalariform.ScalaDocChecker" level="warning">
  <parameters>
    <!-- ... -->
    <parameter default="true" type="boolean" name="ignoreOverride"/>
    <parameter default="scaladoc" type="string" name="indentStyle"/>
  </parameters>
</check>
```

However, this will result in `ignoreOverride` being `false` and `indentStyle` defaulting to `AnyDoc`. The `parameter` _XML_ element does not appear to support either a `type` or a `default` attribute - yet _ScalaStyle_ does not issue any complaints and quietly accepts the invalid config.

The correct config should be to put the parameter value within the `parameter` element, as follows:

```xml
<check enabled="true" class="org.scalastyle.scalariform.ScalaDocChecker" level="warning">
  <parameters>
    <!-- ... -->
    <parameter name="ignoreOverride">true</parameter>
    <parameter name="indentStyle">scaladoc</parameter>
  </parameters>
</check>
```

BTW, in the case of `indentStyle`, if you don't enter "scaladoc" or "javadoc", any type of comment formatting is supported. If you accidentally mistype either, all verification is disabled without any error or warning message.

**UPDATE**: It appears that the _example configuration_ in the documentation was copied from the _Scalastyle configuration definition_ - as that does require type and default value information. In case there's any confusion, I'm referencing the documentation of the configuration file itself, and not it's definition.

**Comment by matthewfarwell** [comment]
Fixed by #270.
