### ISSUE TITLE
support for sbt 1.0?

### ISSUE THREAD

**Issue by SethTisue** [scalastyle/scalastyle#271]
it would be nice if the sbt plugin were available for sbt 1.0

**Comment by matthewfarwell** [comment]
Duplicate of https://github.com/scalastyle/scalastyle-sbt-plugin/issues/62

**Comment by matthewfarwell** [comment]
Will be releasing in the next couple of days.

**Comment by matthewfarwell** [comment]
Fixed and released actually.
