### ISSUE TITLE
"Invalid doc style" warning if implicit def is first code in an object

### ISSUE THREAD

**Issue by lfrost** [scalastyle/scalastyle#277]
For indentStyle scaladoc, if the first code in an object is an implicit def, scalastyle 1.0.0 gives an "Invalid doc style" warning.  This does not happen if other code is inserted above the implicit def, or if the def is not implicit.

There is another possibly related issue.  If there is a comment before the first scaladoc in a file, there is also an "Invalid doc style" warning.  This  does not happen if there is nothing before the first scaladoc, or if some code is added between the header comment and the first scaladoc.

I have attached code showing both of these.  Foo1.scala has no warnings, Foo2.scala has both warnings, and Foo3.scala shows how each warning can be fixed in a different way than in Foo1.scala.  Below is the CLI output for each.

```
$ java -jar scalastyle_2.12-1.0.0-batch.jar --config scalastyle-config.xml Foo1.scala
Processed 1 file(s)
Found 0 errors
Found 0 warnings
Finished in 460 ms
$ java -jar scalastyle_2.12-1.0.0-batch.jar --config scalastyle-config.xml Foo2.scala
warning file=/home/lfrost/scalastyle/Foo2.scala message=Missing or badly formed ScalaDoc: Invalid doc style line=9
warning file=/home/lfrost/scalastyle/Foo2.scala message=Missing or badly formed ScalaDoc: Invalid doc style line=19
Processed 1 file(s)
Found 0 errors
Found 2 warnings
Finished in 456 ms
$ java -jar scalastyle_2.12-1.0.0-batch.jar --config scalastyle-config.xml Foo3.scala
Processed 1 file(s)
Found 0 errors
Found 0 warnings
Finished in 466 ms`
```

[scalastyle-scaladoc-test.zip](https://github.com/scalastyle/scalastyle/files/1273122/scalastyle-scaladoc-test.zip)

**Comment by matthewfarwell** [comment]
Thanks. I'll have a look at this when I have a little time.
