### ISSUE TITLE
NullPointerException in scalastyle_2.12-1.0.0

### ISSUE THREAD

**Issue by ctimothy** [scalastyle/scalastyle#279]
I am running the following command on a Windows 10 Pro 64bit machine with JAVA version 1.8.0.74.

java -jar scalastyle_2.12-1.0.0-batch.jar --config scalastyle_config.xml --xmlOutput test.xml --quiet true C:\Streams\main\Manager\src\main\scala\smv

I am getting the following
    Exception in thread "main" java.lang.NullPointerException
            at org.scalastyle.XmlOutput$.printToFile(Output.scala:117)
            at org.scalastyle.XmlOutput$.save(Output.scala:110)
            at org.scalastyle.XmlOutput$.save(Output.scala:96)
            at org.scalastyle.Main$.execute(Main.scala:121)
            at org.scalastyle.Main$.main(Main.scala:99)
            at org.scalastyle.Main.main(Main.scala)

I have tried pointing it at different projects and specific file. I have full read/write access to the folder because the following command works without the XML flag. 

java -jar scalastyle_2.12-1.0.0-batch.jar --config scalastyle_config.xml --quiet true C:\Streams\main\Manager\src\main\scala\smv > test.txt

If turn off --quiet, I get several warnings before the NullPointerException. 

If there is any other information I can provide, please let me know.

**Comment by ctimothy** [comment]
I thought it might be something with our Scala code so I download a Scala file from this project called CommentFilterTest.scala and got the same NullPointerException.

**Comment by matthewfarwell** [comment]
Where are you running this? In what directory: specifically is it in the root directory?

**Comment by ctimothy** [comment]
I am running this from a Windows command window.  I have tried running it as an elevated user and administrator. I have tried putting all files (jar, config, and scala) in the same folder. Still having the issue.

**Comment by matthewfarwell** [comment]
Thank you for that information. I'm trying to find what your current directory is when you run the command. What is the output of the `cd` command (or echo %cd%)?

**Comment by ctimothy** [comment]
The output of the cd command is for each of the locations I tried to run the jar

1.  C:\Temp\ScalaStyle
2. C:\Stream\Main\Client\TestApp\GUI\Src\Main\scala
3. F:\ 

Option #3 is a thumb drive with the jar, config, and scala file located in the same folder.

**Comment by matthewfarwell** [comment]
I think I've fixed this. Can you try this with 1.1.0-SNAPSHOT, and tell me if this works. If not, please re-open this issue.

**Comment by ctimothy** [comment]
Cool, I will test it out. Can you point me to where or how to get 1.1.0-SNAPSHOT?

**Comment by matthewfarwell** [comment]
You can get in from sonatype: https://oss.sonatype.org/service/local/repositories/snapshots/content/org/scalastyle/scalastyle_2.12/1.1.0-SNAPSHOT/scalastyle_2.12-1.1.0-20171004.080250-1-batch.jar for instance.

**Comment by ctimothy** [comment]
Great news, the issue is fixed. Thanks!

java -jar scalastyle_2.12-1.1.0-20171004.080250-1-batch.jar  --config scalastyle_config.xml --xmlOutput test.xml CommentFilterTest.scala
error file=E:\\CommentFilterTest.scala message=expected class or object definition
Processed 1 file(s)
Found 1 errors
Found 0 warnings
Finished in 3047 ms
