### ISSUE TITLE
objectFieldRegex field in FieldNamesChecker doesn't seem to actually work?

### ISSUE THREAD

**Issue by elementlipeng** [scalastyle/scalastyle#280]
I'm using scalastyle 1.0.0 with Scala 2.11, and it seems like all of my constants vals in Objects are judged using the default field regex instead of the objectFieldRegex, so that `val Blarghh = "constant"` gets a warning because it doesn't start with a lower case character, while objectRegexFied is set to ^[A-Z][A-Za-z0-9]*$. Why is that?

**Comment by matthewfarwell** [comment]
Do you have a small project which can reproduce this behaviour?

**Comment by elementlipeng** [comment]
Ok upon further investigation, looks like I was using an older version of scalastyle. Brew's scalastyle version in only up to 0.8, and Intellij's scalastyle version might be even older? 1.0.0 seems to work fine. Wish Brew/Intellij had that though. Closing for now.

**Comment by matthewfarwell** [comment]
Cool. It's always nice when that happens. For the upgrade in intellij, please vote for https://youtrack.jetbrains.com/issue/SCL-12301.

**Comment by matthewfarwell** [comment]
And if you want this in brew, I think this is what you have to change: https://github.com/Homebrew/homebrew-core/blob/master/Formula/scalastyle.rb
