### ISSUE TITLE
CovariantEqualsChecker still triggers for scala.Any

### ISSUE THREAD

**Issue by nrinaudo** [scalastyle/scalastyle#281]
The following code triggers `CovariantEqualsChecker`:

```scala
override def equals(o: scala.Any) = ???
```

While the following does not:

```scala
override def equals(o: Any) = ???
```

It's a weird corner case, since most sane people don't write `scala.Any`, but apparently I'm not sane.

**Comment by matthewfarwell** [comment]
Fixed by #282
