### ISSUE TITLE
Wrong rule in default_config.xml

### ISSUE THREAD

**Issue by BalmungSan** [scalastyle/scalastyle#298]
Hello, 

[this line](https://github.com/scalastyle/scalastyle/blob/54198e2946be19d01e28635c2997741800b0e09c/src/main/resources/default_config.xml#L140) in the [_default\_config.xml_](https://github.com/scalastyle/scalastyle/blob/master/src/main/resources/default_config.xml) file is wrong, it should be [**ProcedureDeclarationChecker**](https://github.com/scalastyle/scalastyle/blob/master/src/main/scala/org/scalastyle/scalariform/ProcedureDeclarationChecker.scala) instead of **ProcedureDefinitionChecker**.

**Comment by matthewfarwell** [comment]
Do you want to do a PR? If not, I will do it in the next week or so.

**Comment by BalmungSan** [comment]
It was so simple that I didn't think in doing a PR, but if you want i'll do it right away.

**Comment by mwz** [comment]
Hi @matthewfarwell, any plans to make a release with this fix anytime soon?

**Comment by matthewfarwell** [comment]
Yes, I will be doing a release in the next couple of weeks.
