### ISSUE TITLE
MethodLengthChecker - provision to ignore blank lines in a method.

### ISSUE THREAD

**Issue by piyushjainsn** [scalastyle/scalastyle#300]
org.scalastyle.scalariform.MethodLengthChecker

it counts blank lines as well to check method length. can we have a parameter like below to ignore blank lines so they don't contribute to the calculation of method length.

<parameter name="ignoreBlankLines"><![CDATA[true]]></parameter>

**Comment by canoztokmak** [comment]
Submitted #301 for this PR.

**Comment by canoztokmak** [comment]
can be closed since pr is merged..

**Comment by matthewfarwell** [comment]
Fixed by #301.
