### ISSUE TITLE
PackageNamesChecker default regex allows uppercase

### ISSUE THREAD

**Issue by anilkumarmyla** [scalastyle/scalastyle#310]
As per scala/java naming conventions, package names are written in all lower case. But the default regex and documentation point to a regex that allows camelcase package names
```
class PackageNamesChecker extends ScalariformChecker {
val DefaultRegex = "^[a-z][A-Za-z]*$"
```

**Comment by matthewfarwell** [comment]
Thanks. Do you want to do a PR for this?

**Comment by anilkumarmyla** [comment]
I'll give it a try!

**Comment by mwz** [comment]
This was released in https://github.com/beautiful-scala/scalastyle/releases/tag/v1.3.0.
