### ISSUE TITLE
Custom Rules

### ISSUE THREAD

**Issue by sathishbabu96** [scalastyle/scalastyle#311]
How can I write a custom rule?

**Comment by matthewfarwell** [comment]
You can copy one of the existing rules, and then include it as a jar on the classpath. You will also need to include the messages (look at src/main/resources/reference.conf)

**Comment by sathishbabu96** [comment]
I am asking how to write custom rules not how to add the rule to my project. Is there any package and any semantics to follow for writing custom rules?

**Comment by JODUVENKATAKISHOR** [comment]
> I am asking how to write custom rules not how to add the rule to my project. Is there any package and any semantics to follow for writing custom rules?

even i am also trying, how to write scala custom rules, if u found anywhere, inform me also jvkbrdid@gmail.com
