### ISSUE TITLE
Cyclomatic complexity not correct

### ISSUE THREAD

**Issue by pysa** [scalastyle/scalastyle#33]
Hi,

I noted that some function would be spotted as having a too high cyclomatic complexity if local functions are used. Putting the local functions outside (as non local) solves the issue. In my opinion, this is erroneous. Locally defined functions should not be counted in cyclomatic complexity of the enclosing function.

Pierre-Yves

**Comment by rklaehn** [comment]
+1! Moving inner helper methods outside does not improve code quality. So both method length and cyclomatic complexity should be configurable to allow for a more functional style.

**Comment by matthewfarwell** [comment]
@rklaehn @wookietreiber @pysa Can you test this with the latest snapshot, and tell me if this is better for you please?

Thanks.

**Comment by rklaehn** [comment]
@matthewfarwell Is there an easy way to test the latest snapshot using sbt scalastyle plugin?

**Comment by matthewfarwell** [comment]
Yes, there is, but since I've just released 0.8.0, you can test it with that.
