### ISSUE TITLE
HeaderMatchesChecker : seemingly not working.

### ISSUE THREAD

**Issue by gavinbaumanis** [scalastyle/scalastyle#333]
I have the following in the .xml file 
```
<check class="org.scalastyle.file.HeaderMatchesChecker" level="warning"
		enabled="true">
		<parameters>
                <parameter name="header"><![CDATA[/**
  * Copyright (C) 2014-2018. Gavin Baumanis. All Rights Reserved.
  *
  * E: gavinbaumanis@gmail.com
  *
  */]]></parameter>
		</parameters>
	</check>

```

and I have the following at the start of the file;
```
/**
  * Copyright (C) 2014-2018. Gavin Baumanis. All Rights Reserved.
  *
  * E: gavinbaumanis@gmail.com
  *
  */

```
yet;
sbt scalastyle still reports 

> Header does not match expected text

I am happy to concede that I have something wrong in the XML...
But I have been trying to get this setting to work for more than two hours now and am now giving up and asking for some help - Thanks!

**Comment by anilkumarmyla** [comment]
This works for me. Were you able to resolve this @gavinbaumanis . If not, what version of scalastyle are you using ? Any reproduction steps should help solving this faster

**Comment by gavinbaumanis** [comment]
Hi there,
I have absolutely no idea what was causing the issue.

I ended up deleting my workspace, retrieving a fresh copy of the source code from version control and also re-installed sbt, too.

Most sensible answer is an issue in the XML - but I really don't know;
The code now passes stylecheck, correctly.
