### ISSUE TITLE
can not open this web. http://www.scalastyle.org

### ISSUE THREAD

**Issue by LearnerFate** [scalastyle/scalastyle#345]
![image](https://user-images.githubusercontent.com/7939517/62438017-31bded80-b778-11e9-9da8-f1c67ba336ec.png)

![image](https://user-images.githubusercontent.com/7939517/62438078-6f227b00-b778-11e9-950c-cb96bade162f.png)

**Comment by ericmarkmartin** [comment]
I believe scalastyle migrated to github pages: http://scalastyle.github.io/. They should really update this—in the README as well
